### ISSUE TITLE
只能上线本机

### ISSUE THREAD

**Issue by Zer08Bytes** [Cc28256/CcRemote#10]
？。

**Comment by chz2008** [comment]
是不是需要重新编译AntiVirus.sln 和 Loder.sln？？？

**Comment by Cc28256** [comment]
1 你的控制UI端设置的ip必须和当前的主机ip设置为相同的，你生成的被控端随便放。
2 设置主机ip后生成的被控端文件在CcRemote.exe同级目录下的server.exe和sexrcs.png文件

**Comment by chz2008** [comment]
我是直接使用你bin下的生成好的测试的。

**Comment by Cc28256** [comment]
对啊 那不应该啊 没有人遇到过你这样的问题。。你界面UI生成设置那里填写的什么？

**Comment by chz2008** [comment]
是的

**Comment by chz2008** [comment]
你看配置文件就知道，我是在服务器端(192.168.1.250)上设置和生成的

**Comment by chz2008** [comment]
我来截图给您看吧

**Comment by Cc28256** [comment]
![image](https://user-images.githubusercontent.com/50364169/223007539-59c94a82-2ec7-4b89-93f4-888a8425de0c.png)
这里你填的什么?

**Comment by chz2008** [comment]
我来截图。填写的是192.168.1.250 和 6000

**Comment by chz2008** [comment]
哎，不知道怎么上传图片。

**Comment by Cc28256** [comment]
你的主机ip是192.168.1.250 监听端口设置的是6000并且执行成功 生成设置填写的192.168.1.250 和 6000，生成后，将server.exe拿到了局域网或者虚拟机可ping通的其他机器，文件没有被杀软查杀、没有被其他工具拦截，如果这些都符合，那我也不知道怎么回事了。

**Comment by chz2008** [comment]
方便加一下微信吗  我的是wxid_v1n2p26ye77222   谢谢

**Comment by Cc28256** [comment]
你要不留个qq吧

**Comment by chz2008** [comment]
2793335990

**Comment by chz2008** [comment]
太奇怪了，上线不了

**Comment by kidxxx** [comment]
不是上线不了 是因为你运行了多个，上线也是上线到你上一个配置 哈哈哈哈，还有就是获取不了win7以上的版本信息，显示为null

**Comment by kidxxx** [comment]
我看了原因是生成的dll文件在使用中  释放替换失败，源码中把这个名字改改或者随机名字就可解决

**Comment by todis21** [comment]
楼主有QQ群聊吗?方便讨论

**Comment by Cc28256** [comment]
没有哦 这个还是当初学习时看的 你照着注释和结构图学习也很容易上手的 这个只能作为参考 现在这个代码有点落后了
