### ISSUE TITLE
TestLoadDll  project      __asm {	call buffer}  执行异常

### ISSUE THREAD

**Issue by cyfbj** [Cc28256/CcRemote#3]
您在调试时   call buffer 可以正常执行？

**Comment by Cc28256** [comment]
因为工作的原因已经不更新了，所以你要手动找到导出函数地址call过去，本来是更改4D 5A 构造跳转 jmp 到导出函数，但是都是手动改的，没有写成工具。（找到buffer内存中pe文件导出函数的地址call过去就行了）

**Comment by Cc28256** [comment]
导出函数是反射加载自身，他会自己找到PE头然后分配空间，修复各个区段、导入表、导出表、重定位加载，取代了loadlibrary函数。：）希望对你有帮助
