### ISSUE TITLE
程序报错了提示文件操作错误我是win7xit

### ISSUE THREAD

**Issue by heiyanmaster** [Cc28256/CcRemote#7]
<img src="https://raw.githubusercontent.com/heiyanmaster/yifeichonggui/master/xm.png">

**Comment by Cc28256** [comment]
你要保证文件目录都是对的，他会去找子文件夹修改配置生成文件，可能是没有找到文件，不要单复制一个主程序

**Comment by heiyanmaster** [comment]
还有一个问题就是运行服务端会突然闪过一个cmd窗口？
