### ISSUE TITLE
新问题

### ISSUE THREAD

**Issue by heiyanmaster** [Cc28256/CcRemote#8]
还有一个问题就是运行服务端会突然闪过一个cmd窗口？

**Comment by Cc28256** [comment]
你可以把他改成窗口程序。那样就不会由ui显示了

**Comment by heiyanmaster** [comment]
怎么修改啊不懂

**Comment by Cc28256** [comment]
项目属性 连接器 系统 子系统 
改完之后代码也要改一改
这些东西google一下就行了

**Comment by heiyanmaster** [comment]
好复杂啊，当初你没想过不要cmd窗口么....

**Comment by Cc28256** [comment]
我当初是想看看框架和原理，你也可以写个bat脚本 cmd /c tiojan.exe 执行 窗口就是隐藏的了

**Comment by heiyanmaster** [comment]
哭了

**Comment by wgetnz** [comment]
#pragma comment( linker, "/subsystem:\"windows\" /entry:\"mainCRTStartup\"" )
