### ISSUE TITLE
上线

### ISSUE THREAD

**Issue by Zer08Bytes** [Cc28256/CcRemote#9]
只能上线本机？

**Comment by Cc28256** [comment]
可能是你局域网的问题 你可以尝试2台机器之间是否能够互相ping通

**Comment by Cc28256** [comment]
并且只需要设置服务器ip 不需要知道客户端ip是多少

**Comment by chz2008** [comment]
我的配置文件是：
[Settings]
ListenPort=6000
MaxConnection=1000
ListemIp=192.168.1.250
生成的服务端，放到局域网任何机器都执行不了。(当然，局域网都能互相ping通的哟)
telnet  192.168.1.250 端口6000到服务器端口都是通的，防火墙也关闭了。
生成的这个服务端，如果放到 192.168.1.250是可以上线的，上线的ip显示是127.0.0.1
但是这个服务端放到我的其他机器，比如192.168.1.10上，是上不了线的。请问这个是什么原因。
